name: python-check
# XXX I think we eventually want maybe on pull_request, and push just to master
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # using lower case typing notation for collections, which requries Python 3.9+
        # XXX is 3.11 supported?
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run various checks
        run: |
          check.sh
