name: python-check
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # using lower case typing notation for collections, which requries Python 3.9+
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run various checks
        run: |
          ./check.sh
